// AtlasExperience: the codebase as ONE connected, walkable flow.
//
// The backend designs a tour (entry point -> core -> supporting cast). We turn
// that into a single connected PATH and lay it out cleanly on the frontend
// (short links, even spacing). The user steps node-to-node with Prev / Next (or
// by clicking a node), reads its description in the LEFT pane, and presses Play
// to hear it. They can also pan/zoom the whole view freely.
//
// Everything (graph + tour + a description per node) is pre-generated by the
// backend, so each step is an instant memory read.

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  fetchGraph, fetchTour, fetchNarration, askQuestion,
  startBuild, fetchBuildStatus, type BuildStatus,
} from "./api";
import type { GraphDoc, GraphNode } from "./types";
import { AtlasMap } from "./components/AtlasMap";
import { NodePanel } from "./components/NodePanel";
import { ChatPanel, type ChatMessage } from "./components/ChatPanel";
import { HomePage } from "./components/HomePage";
import { BuildProgress } from "./components/BuildProgress";
import { useSpeech } from "./hooks/useSpeech";

interface AtlasProps {
  onExit: () => void;
}

export function AtlasExperience({ onExit }: AtlasProps) {
  const [doc, setDoc] = useState<GraphDoc | null>(null);
  const byIdRef = useRef<Map<string, GraphNode>>(new Map());

  const [path, setPath] = useState<GraphNode[]>([]);   // ordered, deduped flow
  const pathRef = useRef<GraphNode[]>([]);
  useEffect(() => { pathRef.current = path; }, [path]);
  const [current, setCurrent] = useState(0);

  const [loading, setLoading] = useState(true);
  const [loadingMsg, setLoadingMsg] = useState("Loading the atlas…");

  const [desc, setDesc] = useState("");
  const descRef = useRef("");
  useEffect(() => { descRef.current = desc; }, [desc]);
  const [descLoading, setDescLoading] = useState(false);

  // ---- auto-play ("Render") mode ----
  const [rendering, setRendering] = useState(false);   // an auto-tour session is engaged
  const [playing, setPlaying] = useState(false);       // actively reading + advancing
  const playingRef = useRef(false);
  useEffect(() => { playingRef.current = playing; }, [playing]);

  const [chatOpen, setChatOpen] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [thinking, setThinking] = useState(false);

  const speech = useSpeech();

  // ---- client-side description cache ----
  const narrCache = useRef<Map<string, string>>(new Map());
  const getNarration = useCallback(async (nodeId: string) => {
    const hit = narrCache.current.get(nodeId);
    if (hit) return hit;
    const text = await fetchNarration(nodeId);
    narrCache.current.set(nodeId, text);
    return text;
  }, []);

  // ---- boot: load graph + build the connected path from the tour ----
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const g = await fetchGraph();
        if (cancelled) return;
        byIdRef.current = new Map(g.nodes.map((n) => [n.id, n]));
        setDoc(g);

        const tour = await fetchTour().catch(() => null);
        if (cancelled) return;

        // Build a single connected path. Start from the tour order; dedupe so we
        // never show "main -> main -> app". Fall back to entry points + modules.
        const ordered: string[] = [];
        const seen = new Set<string>();
        const push = (id?: string | null) => {
          if (id && !seen.has(id) && byIdRef.current.has(id)) {
            seen.add(id); ordered.push(id);
          }
        };
        (tour?.stops ?? []).forEach((s) => push(s.nodeId));
        g.entryPoints.forEach(push);
        g.nodes.filter((n) => n.kind === "module").forEach((n) => push(n.id));

        const nodes = ordered.map((id) => byIdRef.current.get(id)!).filter(Boolean);
        setPath(nodes);
        setLoading(false);
      } catch (e: any) {
        setLoadingMsg(`Failed to load: ${e.message}`);
      }
    })();
    return () => { cancelled = true; };
  }, []);

  // ---- fetch the description whenever the focused node changes ----
  // In auto-play ("Render") mode, once the text is ready we speak it and, when
  // speech ends, advance to the next node — which re-runs this effect and chains
  // on to the end of the flow.
  useEffect(() => {
    const node = path[current];
    if (!node) return;
    speech.stop();
    setDesc("");
    setDescLoading(true);
    let cancelled = false;
    (async () => {
      let text: string;
      try {
        text = await getNarration(node.id);
      } catch {
        text = node.signature || "No description available.";
      }
      if (cancelled) return;
      setDesc(text);
      setDescLoading(false);

      if (playingRef.current) {
        speech.speak(text, () => {
          if (!playingRef.current) return;
          const nextIdx = current + 1;
          if (nextIdx < pathRef.current.length) {
            setTimeout(() => { if (playingRef.current) setCurrent(nextIdx); }, 500);
          } else {
            // Reached the end of the flow.
            setPlaying(false);
            setRendering(false);
          }
        });
      }
    })();
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [current, path]);

  const goTo = useCallback((i: number) => {
    setCurrent(() => Math.max(0, Math.min(pathRef.current.length - 1, i)));
  }, []);

  // Manual step. If a render session is engaged, keep auto-reading from the new
  // node (user "clicks next node -> it starts automatically"); otherwise just move.
  const next = useCallback(() => {
    if (rendering) setPlaying(true);
    goTo(current + 1);
  }, [current, goTo, rendering]);

  const prev = useCallback(() => {
    if (rendering) setPlaying(true);
    goTo(current - 1);
  }, [current, goTo, rendering]);

  // Manual single-node play (normal mode) — speak just this node, no advancing.
  const onPlay = useCallback(() => { if (desc) speech.speak(desc); }, [desc, speech]);
  const onPause = useCallback(() => { speech.stop(); }, [speech]);

  // ---- Render (auto-play) controls ----
  const startRender = useCallback(() => {
    speech.stop();
    setRendering(true);
    setPlaying(true);
    if (current === 0) {
      // Already at the start: nudge the effect to (re)read node 0.
      setCurrent(-1);
      setTimeout(() => setCurrent(0), 0);
    } else {
      setCurrent(0);
    }
  }, [current, speech]);

  const pauseRender = useCallback(() => {
    setPlaying(false);
    speech.stop();
  }, [speech]);

  const resumeRender = useCallback(() => {
    setPlaying(true);
    // Re-speak the current node and continue the chain.
    if (descRef.current) {
      speech.speak(descRef.current, () => {
        if (!playingRef.current) return;
        const nextIdx = current + 1;
        if (nextIdx < pathRef.current.length) {
          setTimeout(() => { if (playingRef.current) setCurrent(nextIdx); }, 500);
        } else { setPlaying(false); setRendering(false); }
      });
    }
  }, [current, speech]);

  const stopRender = useCallback(() => {
    setPlaying(false);
    setRendering(false);
    speech.stop();
  }, [speech]);

  // ---- Q&A: jump the flow to the answer's node ----
  const onAsk = useCallback(
    async (question: string) => {
      speech.stop();
      setMessages((m) => [...m, { role: "user", content: question }]);
      setThinking(true);
      try {
        const hist = messages.map((m) => ({ role: m.role, content: m.content }));
        const res = await askQuestion(question, hist);
        const node = res.nodeId ? byIdRef.current.get(res.nodeId) : null;
        setMessages((m) => [
          ...m,
          { role: "assistant", content: res.answer, navNodeId: res.nodeId, navLabel: node?.fullLabel ?? null },
        ]);
        if (res.nodeId && node) {
          narrCache.current.set(res.nodeId, res.answer);
          jumpToNode(res.nodeId);
        }
      } catch (e: any) {
        setMessages((m) => [...m, { role: "assistant", content: `Something went wrong: ${e.message}` }]);
      } finally {
        setThinking(false);
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [messages, speech, path]
  );

  // Move focus to a node, appending it to the path if it isn't on it yet.
  const jumpToNode = useCallback((nodeId: string) => {
    const idx = path.findIndex((n) => n.id === nodeId);
    if (idx >= 0) { goTo(idx); return; }
    const node = byIdRef.current.get(nodeId);
    if (!node) return;
    setPath((p) => {
      const np = [...p, node];
      setCurrent(np.length - 1);
      return np;
    });
  }, [path, goTo]);

  const node = path[current] ?? null;

  return (
    <div className="stage">
      {/* Left pane: focused node's description + Play/Pause + Prev/Next */}
      <NodePanel
        node={node}
        index={current}
        total={path.length}
        text={desc}
        loading={descLoading}
        speaking={speech.speaking}
        mark={speech.mark}
        rendering={rendering}
        playing={playing}
        onPlay={onPlay}
        onPause={onPause}
        onPrev={prev}
        onNext={next}
        onStartRender={startRender}
        onPauseRender={pauseRender}
        onResumeRender={resumeRender}
        onStopRender={stopRender}
      />

      {/* The connected flow map */}
      {path.length > 0 && (
        <AtlasMap path={path} current={current} onSelect={goTo} />
      )}

      {/* Top bar */}
      <div className="topbar">
        <div className="brand">
          <div className="brand-mark">◈</div>
          <div>
            <div className="brand-title">Codebase Atlas</div>
            <div className="brand-sub">a living map of your code</div>
          </div>
        </div>
        {doc && (
          <div className="repo-chip">
            <span className="dot" />
            <span><b>{doc.repo.name}</b></span>
            <span>{doc.repo.fileCount} files</span>
            <span>{doc.stats.nodeCount} nodes</span>
            <button className="btn" onClick={() => setChatOpen((o) => !o)}>
              {chatOpen ? "Hide guide" : "💬 Ask the guide"}
            </button>
            <button className="btn" title="Analyze a different repository"
              onClick={() => { speech.stop(); onExit(); }}>
              ↩ New repo
            </button>
          </div>
        )}
      </div>

      {/* Q&A chat (optional) */}
      <ChatPanel
        visible={chatOpen}
        messages={messages}
        thinking={thinking}
        onSend={onAsk}
        onNavClick={jumpToNode}
        onClose={() => setChatOpen(false)}
      />

      {/* Loading overlay */}
      {loading && (
        <div className="loading">
          <div className="loading-inner">
            <div className="loading-ring" />
            <div className="loading-title">Building the atlas</div>
            <div className="loading-sub">{loadingMsg}</div>
          </div>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// App: the top-level phase router.
//   home      -> collect repo URL + PAT, kick off the build
//   building  -> poll progress while everything is pre-generated
//   atlas     -> the connected, walkable map
// ---------------------------------------------------------------------------
type Phase = "home" | "building" | "atlas";

export function App() {
  const [phase, setPhase] = useState<Phase>("home");
  const [status, setStatus] = useState<BuildStatus | null>(null);
  const [homeError, setHomeError] = useState<string | null>(null);
  const [booting, setBooting] = useState(true);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const s = await fetchBuildStatus();
        if (cancelled) return;
        if (s.ready) setPhase("atlas");
        else if (["cloning", "parsing", "tour", "narrating"].includes(s.status)) {
          setStatus(s);
          setPhase("building");
        }
      } catch { /* backend not up yet; stay on home */ }
      finally { if (!cancelled) setBooting(false); }
    })();
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    if (phase !== "building") return;
    let stop = false;
    const tick = async () => {
      try {
        const s = await fetchBuildStatus();
        if (stop) return;
        setStatus(s);
        if (s.ready) { setPhase("atlas"); return; }
        if (s.status === "error") return;
      } catch { /* transient */ }
      if (!stop) setTimeout(tick, 1000);
    };
    tick();
    return () => { stop = true; };
  }, [phase]);

  const onStart = useCallback(async (url: string, pat: string, branch: string) => {
    setHomeError(null);
    try {
      const s = await startBuild(url, pat, branch);
      setStatus(s);
      setPhase("building");
    } catch (e: any) {
      setHomeError(e.message || "Failed to start build.");
    }
  }, []);

  const onExit = useCallback(() => {
    setStatus(null);
    setHomeError(null);
    setPhase("home");
  }, []);

  if (booting) {
    return (
      <div className="loading">
        <div className="loading-inner">
          <div className="loading-ring" />
          <div className="loading-sub">connecting…</div>
        </div>
      </div>
    );
  }

  if (phase === "atlas") return <AtlasExperience onExit={onExit} />;
  if (phase === "building" && status) {
    return <BuildProgress status={status} onRetry={onExit} />;
  }
  return <HomePage onStart={onStart} error={homeError} />;
}
